"""empty message

Revision ID: 932493c17eba
Revises: a5cffa318ac2
Create Date: 2025-10-16 01:05:29.686873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932493c17eba'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('raza', sa.String(length=120), nullable=False),
    sa.Column('origen', sa.String(length=120), nullable=False),
    sa.Column('color_de_ojos', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('poblacion', sa.Integer(), nullable=False),
    sa.Column('clima', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planeta_id', sa.Integer(), nullable=False),
    sa.Column('personaje_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personaje_id'], ['personaje.id'], ),
    sa.ForeignKeyConstraint(['planeta_id'], ['planeta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('fecha_de_subscripcion', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint(None, ['nombre'])
        batch_op.create_unique_constraint(None, ['apellido'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('fecha_de_subscripcion')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    op.drop_table('favoritos')
    op.drop_table('planeta')
    op.drop_table('personaje')
    # ### end Alembic commands ###
